query getRsvp {
  rsvp {
    accept
    addGuest
    age
    body
    decline
    error
    firstName
    lastName
    removeGuest
    successAccept
    successDecline
    addMoreGuests
    captchaChallenge
  }
}
