query getSaveTheDate {
  getSaveTheDate {
    coupleNames
    dateTime
    location
    photos {
      photo {
        caption
        credit
        description
        filename
        path
        title
      }
    }
    title
  }
}
