/**
 * Mark Down Component Component
 * which styles the HTML Elements generated by the "react-markdown" component
 */
import { PALETTE } from 'Constants/PALETTE';
import styledComponents from 'styled-components';

const MarkdownWrapper: React.FunctionComponent = styledComponents.div`
  font-family: Merienda, sans-serif;
  font-size: 0.85em;

  h1,
  h2,
  h3 {
    font-family: Rochester, sans-serif;
    color: ${PALETTE.DARK_CYAN};
    display: block;
    position: relative;
    z-index: 1;
    font-weight: normal;
    margin: 0;

    img {
      display: block;
      border: 4px solid lightgray;
      margin: -0.25em 0 0.25em 0.25em;
      z-index: -1;
      position: relative;
      max-width: 50vw;

      &.no-border {
        margin: 0.25em 0 0.25em 0.25em;
        border: none;
      }
    }
  }

  h1 {
    font-size: 2.9em;
    font-weight: normal;
    padding: 0;
    margin: -1em 0 0 0;
    text-align: right;
    float: right;
  }

  h2 {
    font-size: 2em;
  }

  h3 {
    font-size: 1.5em;
  }

  p {
    line-height: 1.75em;
  }

  .clear {
    clear: both;
  }

  > span {
    img:nth-of-type(1) {
      float: left;
      margin: 0.25em 1em 0.25em 0;
      max-width: 50vw;
      border: 4px solid lightgray;
    }
  }

  a {
    color: ${PALETTE.DARK_RED};
    text-decoration: none;
    text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.25);

    &:hover {
      text-decoration: underline;
    }
  }

  ul {
    list-style: none;
    line-height: 2em;
  }

  @media (min-width: 768px) {
    font-size: 0.8em;
  }

  @media (min-width: 1024px) {
    font-size: 1em;
  }

  @media (min-width: 450px) and (max-width: 550px) {
    p:nth-of-type(1) {
      padding-top: 2em;
    }
  }

  @media (min-width: 551px) and (max-width: 600px) {
    p:nth-of-type(1) {
      padding-top: 2.5em;
    }
  }

  @media (min-width: 601px) and (max-width: 768px) {
    p:nth-of-type(1) {
      padding-top: 2.5em;
    }
  }

  @media (min-width: 769px) and (max-width: 800px) {
    p:nth-of-type(1) {
      padding-top: 4em;
    }
  }

  @media (min-width: 801px) and (max-width: 850px) {
    p:nth-of-type(1) {
      padding-top: 5em;
    }
  }

  @media (min-width: 851px) and (max-width: 1000px) {
    p:nth-of-type(1) {
      padding-top: 6em;
    }
  }

  @media (min-width: 1001px) and (max-width: 1023px) {
    p:nth-of-type(1) {
      padding-top: 7em;
    }
  }

  @media (min-width: 1024px) and (max-width: 1150px) {
    p:nth-of-type(1) {
      padding-top: 5em;
    }
  }
`;

export { MarkdownWrapper };
